name: set-variables

runs:
  using: "composite"
  steps:
    - name: Setup Variables
      shell: bash
      run: |
        # workaround for variable substition in variable
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/variables#passing-values-between-steps-and-jobs-in-a-workflow
        echo "VM=${RELEASE}-vm-01" >> $GITHUB_ENV
        echo "HOME_IN_LXC=/home/${USERNAME_IN_LXC}" >> $GITHUB_ENV
        echo "LXC_CMD_PREFIX=su --login ${USERNAME_IN_LXC} -c" >> $GITHUB_ENV
        echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

