name: build-deb-and-autopkgtest

on:
  push:
  pull_request:

env:
  # in 2024 Aug, Github Action provides 4 cores / 16G memory / 19G disk
  # see "default github action resource" below
  RELEASE: "sid"
  CPU: "2"
  MEMORY: "8GB"
  DISK: "16GB"
  USERNAME_IN_LXC: "tai"

jobs:
  VERIFICATION_01_LOCAL_ENV_Build_Deb_in_LXD_VM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Variables
        uses: ./.github/workflows/01_set_variables

      - name: Launch VM Instance and Build Deb
        uses: ./.github/workflows/02_launch_vm_instance

      - name: Get Ready to Setup Testbed
        run: |
          # begin to setup autopkgtest
          lxc exec ${VM} -- su --login ${USERNAME_IN_LXC} -c "sudo apt update"
          lxc exec ${VM} -- su --login ${USERNAME_IN_LXC} -c "sudo apt install -y autopkgtest"

      - name: Setup Testbed - Autopkgtest Local Env
        run: |
          echo "We will run autopkgtest in the local environment directly so no additional setup is needed."

      - name: Run Test - Autopkgtest Local Env
        run: |
          # start testing with autopkgtest
          lxc exec ${VM} -- su --login ${USERNAME_IN_LXC} -c "cd /home/${USERNAME_IN_LXC}/${REPO_NAME} ; sudo autopkgtest -B ./ --apt-upgrade -- null"

      - name: Functional Testing
        run: |
          lxc exec ${VM} -- bash -c "ls /home/${USERNAME_IN_LXC}/"
          lxc exec ${VM} -- bash -c "apt install -y /home/${USERNAME_IN_LXC}/rshim_*_amd64.deb"

          lxc exec ${VM} -- systemctl is-active rshim

